In [2]:
from tropycal.realtime import Realtime
rt = Realtime()
active_storms = rt.list_active_storms()
storm = rt.get_storm(active_storms[0])

/home/jreniel/.local/lib/python3.9/site-packages/tropycal/realtime/realtime.py:18: UserWarning: Warning: Cartopy is not installed in your python environment. Plotting functions will not work.
  warnings.warn(warn_message)
/home/jreniel/.local/lib/python3.9/site-packages/tropycal/plot/plot.py:16: UserWarning: Warning: Cartopy is not installed in your python environment. Plotting functions will not work.
  warnings.warn("Warning: Cartopy is not installed in your python environment. Plotting functions will not work.")
/home/jreniel/.local/lib/python3.9/site-packages/tropycal/tracks/plot.py:25: UserWarning: Warning: Cartopy is not installed in your python environment. Plotting functions will not work.
  warnings.warn("Warning: Cartopy is not installed in your python environment. Plotting functions will not work.")
/home/jreniel/.local/lib/python3.9/site-packages/tropycal/tornado/dataset.py:21: UserWarning: Warning: Cartopy is not installed in your python environment. Plotting functions will not work.
  warnings.warn(warn_message)
/home/jreniel/.local/lib/python3.9/site-packages/tropycal/tornado/plot.py:21: UserWarning: Warning: Cartopy is not installed in your python environment. Plotting functions will not work.
  warnings.warn("Warning: Cartopy is not installed in your python environment. Plotting functions will not work.")
/home/jreniel/.local/lib/python3.9/site-packages/tropycal/recon/plot.py:22: UserWarning: Warning: Cartopy is not installed in your python environment. Plotting functions will not work.
  warnings.warn("Warning: Cartopy is not installed in your python environment. Plotting functions will not work.")

--> Starting to read in current storm data
--> Completed reading in current storm data (5.19 seconds)

In [3]:
df = storm.to_dataframe()

In [4]:
df

,date,extra_obs,special,type,lat,lon,vmax,mslp,wmo_basin
0,2021-05-19 00:00:00,0,,DB,30.2,-58.3,20,1018,north_atlantic
1,2021-05-19 06:00:00,0,,DB,30.0,-57.6,20,1017,north_atlantic
2,2021-05-19 12:00:00,0,,DB,30.0,-56.9,25,1016,north_atlantic
3,2021-05-19 18:00:00,0,,DB,30.0,-56.2,25,1015,north_atlantic
4,2021-05-20 00:00:00,0,,EX,30.3,-55.4,30,1013,north_atlantic
5,2021-05-20 06:00:00,0,,EX,31.7,-54.6,30,1013,north_atlantic
6,2021-05-20 12:00:00,0,,EX,32.9,-52.3,35,1012,north_atlantic
7,2021-05-20 18:00:00,0,,EX,34.4,-53.7,40,1011,north_atlantic
8,2021-05-21 00:00:00,0,,EX,34.9,-55.0,50,1008,north_atlantic
9,2021-05-21 06:00:00,0,,EX,35.5,-56.7,50,1008,north_atlantic
10,2021-05-21 12:00:00,0,,EX,35.7,-58.7,50,1008,north_atlantic
11,2021-05-21 18:00:00,0,,EX,35.0,-61.2,45,1005,north_atlantic
12,2021-05-22 00:00:00,0,,EX,34.5,-61.8,45,1005,north_atlantic
13,2021-05-22 06:00:00,0,,SS,34.2,-62.1,40,1006,north_atlantic
14,2021-05-22 12:00:00,0,,SS,34.4,-62.8,40,1006,north_atlantic
15,2021-05-22 18:00:00,0,,SS,34.2,-62.6,35,1007,north_atlantic